language: node_js

node_js:
  - 0.8

before_script:
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g bower
  - bower install
  - sleep 1 # let server start

script: grunt test:travis

notifications:
  irc:
    channels: "chat.freenode.net#bs-staff"
    skip_join: true
    on_success: change
    on_failure: change

branches:
  only:
    - master