test: &default
  client_id: Aei1qWhZrzWuXbcm6ghZ5jRyk9VkWWfpgwTlw0nMrkaQB6TruFJDoLNXggdBb6D5TX7GgjMbrtTWvEbJ
  client_secret: EFjKr-72xBtrJCxeVBKN4IZyEVyTcFbeLrPlYEReG-bhl_LGYqXtxuTXG9SQ9tbxZxeozBOM1g8b0MUS
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
